region_name: 'eu-central-1'

sqs:
    queue_names:
        ANY_QUEUE: 'any_queue' # for testing
    visibility_timeout: 30
    aws_if_older_than: 0 # for testing

dispatcher:
    lambda_fun_name: 'decode_dispatcher'
    rule_name: 'decode_dispatcher_rule'
    rate: 5
    python_version: '3.9'

batch:
    compute_env_name: 'decode_compute_env'
    minv_cpus: 0
    maxv_cpus: 16
    instance_types:
    - 'g4dn.xlarge'
    queue_name: 'decode_job_queue'
    job_defs:
        train:
            name: 'decode_train_job_def'
            memory: 8000
            gpu_count: 1
            vcpus: 4
            timeout: 18000
        fit:
            name: 'decode_fit_job_def'
            memory: 8000
            gpu_count: 1
            vcpus: 4
            timeout: 3000

vpc:
    vpc_name: 'decode_vpc'

efs:
    file_system_name: 'decode_filesystem_name'

s3:
    bucket_name: 'decode-bucket'
    logs_expiration: 14
    logs_root_path: 'decode_job_logs'
