region_name: 'eu-central-1'

sqs:
    queue_names:
        ANY_QUEUE: 'any_queue' # for testing
    visibility_timeout: 30
    aws_if_older_than: 0 # for testing

dispatcher:
    lambda_fun_name: 'decode_dispatcher'
    rule_name: 'decode_dispatcher_rule'
    rate: 2 # for testing
    python_version: '3.9'

batch:
    compute_env_name: 'decode_compute_env'
    minv_cpus: 0
    maxv_cpus: 4
    instance_types:
    - 'a1.medium'
    queue_name: 'decode_job_queue'
    job_def_name: 'decode_job_definition'

vpc:
    vpc_name: 'decode_vpc'

efs:
    file_system_name: 'decode_filesystem_name'
